name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  validate-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate manifest.json
        run: node scripts/validate-manifest.js

      - name: Determine version
        id: ver
        run: |
          echo "EXT_VERSION=$(node -p "require('./manifest.json').version")" >> $GITHUB_ENV
          echo "version=$EXT_VERSION" >> $GITHUB_OUTPUT

      - name: Package extension zip
        run: |
          zip -r "visua11y-${EXT_VERSION}.zip" . \
            -x "**/.git/**" "**/.github/**" "**/docs/**" "**/*.md" "**/*.log" "*.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: visua11y-${{ env.EXT_VERSION }}
          path: visua11y-${{ env.EXT_VERSION }}.zip

